runtime: python37
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'service_account.json'
  IMAGE_HIGHT: 20000  #15000
  IMAGE_WIDTH: 18000  #12000
  BUCKET_NAME: 'photo-mosaic-317019-urlsigner'
  PROJECT_NAME: 'photo-mosaic-317019'
  TOPIC_NAME: 'mosaic_topic'
  QUEUE_NAME: 'mosaicqueue'
  QUEUE_LOCATION: 'asia-northeast1'
  CACHE_CLEAR_TIMEOUT: 8 #8 mins

handlers:
- url: /js
  static_dir: static/js
  http_headers:
    vary: Accept-Encoding
    
- url: /images
  static_dir: static/images
  http_headers:
    vary: Accept-Encoding

- url: /css
  static_dir: static/js
  http_headers:
    vary: Accept-Encoding
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app --preload
